// <auto-generated />
using System;
using BigBlueBalancer.Api.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BigBlueBalancer.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201118162157_InitialMySqlMigration")]
    partial class InitialMySqlMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("BigBlueBalancer.Api.Entities.Meeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AttendeePW")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CreateDate")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CreateTime")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DialNumber")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<bool>("HasBeenForciblyEnded")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HasUserJoined")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("InternalMeetingID")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MeetingID")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("ModeratorPW")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ParentMeetingID")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("Running")
                        .HasColumnType("tinyint(1)");

                    b.Property<short>("ServerId")
                        .HasColumnType("smallint");

                    b.Property<string>("VoiceBridge")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("MeetingID");

                    b.HasIndex("ServerId");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("BigBlueBalancer.Api.Entities.Server", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Load")
                        .HasColumnType("double");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("Up")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("BigBlueBalancer.Api.Entities.ServerStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ListenerCount")
                        .HasColumnType("int");

                    b.Property<int>("MeetingsCount")
                        .HasColumnType("int");

                    b.Property<int>("ParticipantCount")
                        .HasColumnType("int");

                    b.Property<short>("ServerId")
                        .HasColumnType("smallint");

                    b.Property<bool>("Up")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("VideoCount")
                        .HasColumnType("int");

                    b.Property<int>("VoiceParticipantCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.ToTable("ServerStats");
                });

            modelBuilder.Entity("BigBlueBalancer.Api.Entities.Meeting", b =>
                {
                    b.HasOne("BigBlueBalancer.Api.Entities.Server", "Server")
                        .WithMany("Meetings")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("BigBlueBalancer.Api.Entities.ServerStats", b =>
                {
                    b.HasOne("BigBlueBalancer.Api.Entities.Server", "Server")
                        .WithMany("Stats")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("BigBlueBalancer.Api.Entities.Server", b =>
                {
                    b.Navigation("Meetings");

                    b.Navigation("Stats");
                });
#pragma warning restore 612, 618
        }
    }
}
